import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import { Hero, Ab, Sevs, News } from "../components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Borla Taxi and Tricycle Association</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="main">
        <Hero />
        <Ab />
        <Sevs />
        <News />
      </main>
    </div>
  );
}
